#!/bin/bash

set -e

MAYHEM_URL="https://demo.forallsecure.com"
MAYHEM_USERNAME="vlussenburg@forallsecure.com"

[ ! -f "mayhem" ] && curl --no-progress-meter -Lo ./mayhem ${MAYHEM_URL}/cli/Linux/mayhem && chmod +x ./mayhem

echo "Log in to Mayhem ${MAYHEM_URL} and Docker registry"
./mayhem login --url ${MAYHEM_URL} --token ${MAYHEM_TOKEN}

REGISTRY=$(./mayhem docker-registry)

echo "${MAYHEM_TOKEN}" | docker login -u ${MAYHEM_USERNAME} --password-stdin ${REGISTRY} 

echo "Do docker build"
docker build --platform=linux/amd64 -t ${REGISTRY}/mayhemit-c:latest .
docker push ${REGISTRY}/mayhemit-c:latest

# Don't start a new run if there's an env arg with a previous RUN
[ -z "${RUN}" ] && RUN=$(./mayhem run . --project parasoft-mayhemit-c --owner forallsecure --image ${REGISTRY}/mayhemit-c:latest --file Mayhemfile)

runName=$(echo ${RUN} | awk -F / '{ print $(NF-1) }');

echo "Waiting for run ${RUN} to complete"
./mayhem wait ${RUN} --owner forallsecure

echo "Downloading Mayhem test suites"
./mayhem download forallsecure/${RUN} -o mayhem_download

cp mayhem_download/testsuite/* testsuite/

rm -rf mayhem_download

echo "Combining all mayhem test cases into CppTest CSV"

echo -n "" > testcases
for testcase in testsuite/*
do
	# format "0";"input_value"\n
	echo -n "\"0\";\"" >> testcases
	cat ${testcase} >> testcases
	echo "\"" >> testcases
done

mv testcases tests/autogenerated/test_mayhemit_mayhem.csv 
